---
- name: check and create f1
  hosts: all
  tasks:
    - name: check for file f1 
      stat:
        path: /home/ubuntu/f1
      register: a
    - name: display o/p of above module
      debug:
        var: a
    - name: create f1 dir
      file:
        name: /home/ubuntu/f1
        state: directory
      when: a.stat.exists == false
...        
