---
- name: setup ci-cd
  hosts: webserver
  gather_facts: false
  become: yes
  tasks:
    - name: install jenkins
      apt:
        name: "{{item.a}}"
        state: present
        update_cache: "{{item.b}}"
      with_items:
        - {a: openjdk-11-jdk, b: yes}
        - {a: git, b: no}
        - {a: maven, b: no}
    - name: download jenkins
      get_url:
        url: "https://get.jenkins.io/war-stable/2.401.3/jenkins.war"
        dest: "/home/ubuntu"
- name: seting up qa and prod server
  hosts: appserver
  become: yes
  tasks:
    - block:
      - name:
        apt: 
          name: "{{item.a}}"
          state: present
          update_cache: "{{item.b}}"
        with_items:
         - {a: tomcat9, b: yes}
         - {a: tomcat9-admin, b: no}
      - name: copy users.xml
        copy:
         src: /home/ubuntu/tomcat-users.xml
         dest: /etc/tomcat9
        notify: restart tomcat
      rescue:
       - name:
         yum:
          name: "{{item.a}}"
          state: present
          update_cache: "{{item.b}}"
         with_items:
          - {a: tomcat9, b: yes}
       - name: copy users.xml
         copy:
          src: /home/ubuntu/tomcat-users.xml
          dest: /etc/tomcat9
         notify: restart tomcat9
  handlers:
    - name: restart tomcat9
      service:
        name: tomcat9
        state: restarted
...

       
