---
- name: creating users
  hosts: all
  gather_facts: false
  tasks: 
     - name: create user
       user: 
        name: "{{a}}"
        password: "{{b}}"

     - name: create a file
       file:
         name: "{{c}}"
         state: "{{d}}"
...

