---
- name: capture os info
  hosts: all
  tasks:
    - name: os name
      debug: 
        msg: "{{ansible_distribution}}"
    - name: os version
      debug:
        msg: "{{ansible_distribution_version}}"
    - name: os version
      debug:
        msg: "{{ansible_distribution_major_version}}"
    - name: os version
      debug:
        msg: "{{ansible_distribution_minor_version}}"
...          

