---
- name: to give execute permission to a file
  hosts: all
  tasks:
    - name:
      stat:
        path: /home/ubuntu/prashant
      register: a
    - name:
      debug:
        var: a
    - name: give execute permission
      file:
        name: /home/ubuntu/prashant
        mode: 777
      when: a.stat.exists == true
...        

